### ISSUE TITLE
Date Header Doesn't Show

### ISSUE THREAD

**Issue by lenichols** [n8armstrong/CalendarView#4]
Implemented the calendar nicely but the heading with the Month does not show above the calendar. What could I be doing wrong?

**Comment by armstrongnate** [comment]
In the screenshots the view controller that contains the calendar view is nested in a `UINavigationController` so that's where the heading comes from. I just set the `title` attribute of the view controller in `viewDidLoad` to the current day and then in the delegate callbacks to the passed in date.

``` swift
extension MyViewController: CalendarViewDelegate {

  func calendarDidSelectDate(date: Moment) {
    title = date.format(dateFormat: "MMMM d, yyyy")
  }

  func calendarDidPageToDate(date: Moment) {
    title = date.format(dateFormat: "MMMM d, yyyy")
  }

}
```

So the heading is not included, you will have to make your own or just use a `UINavigationController` and the `title` field like I did for the screenshots.
